In [1]:
from utils import *

# Manipulate data with `ndarray`
<br>
<center><img src="support/ndarray2.gif" width=400></center>

By design similar to numpy

We’ll start by introducing the `NDArray`, MXNet’s primary tool for storing and transforming data. If you’ve worked with `NumPy` before, you’ll notice that a NDArray is, by design, similar to NumPy’s multi-dimensional array. 

## Get started

To get started, let's import the `ndarray` package (`nd` is shortform) from MXNet.

In [2]:
from mxnet import nd

Next, let's see how to create a 2D array (also called a matrix) with values from two sets of numbers: 1, 2, 3 and 4, 5, 6. This might also be referred to as a tuple of a tuple of integers.

NDArray from tuples

In [3]:
nd.array(((1, 2, 3), (5, 6, 7)))


[[ 1.  2.  3.]
 [ 5.  6.  7.]]
<NDArray 2x3 @cpu(0)>

We can also create a very simple matrix with the same shape (2 rows by 3 columns) but fill it with 1s.

1s

In [4]:
x = nd.ones(shape=(2, 3))
x


[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>

Often we’ll want to create arrays whose values are sampled randomly. 
For example, sampling values uniformly between -1 and 1. Here we create the same shape, but with random sampling.

Randomly sampled

In [5]:
y = nd.random.uniform(low=-1, high=1, shape=(2,3))
y


[[ 0.09762704  0.18568921  0.43037868]
 [ 0.68853152  0.20552671  0.71589124]]
<NDArray 2x3 @cpu(0)>

As with NumPy, the dimensions of each NDArray are accessible by accessing the `.shape` attribute. We can also query its `size`, which is equal to the product of the components of the shape. In addition, `.dtype` tells the data type of the stored values. dtype is important, support for float16

NDArray metadata

In [7]:
(x.shape, x.size, x.dtype, x.context)

((2, 3), 6, numpy.float32, cpu(0))

Type

In [ ]:
nd.ones((2,3), dtype=np.uint8)

In [ ]:
Context

In [ ]:
nd.ones((2,3), ctx=mx.gpu(1))

## Operations

NDArray supports a large number of standard mathematical operations. Such as element-wise multiplication:

In [ ]:
x * y

Exponentiation

In [ ]:
x.exp()

And grab a matrix’s transpose to compute a proper matrix-matrix product:

Matrix multiplication

In [ ]:
x.shape, y.shape

In [ ]:
nd.dot(x, y.T)

## Indexing
<br>
<center><img src="support/ndarray.gif" width=400></center>

Read the 2nd and 3d columns

In [ ]:
y

In [ ]:
y[:, 1:3]

Writing to a specific element

Writing

In [ ]:
y[1:2, 0:2] = 4
y

## Converting between MXNet NDArray and NumPy

Converting MXNet NDArrays to and from NumPy is easy. The converted arrays do not share memory.

In [ ]:
a = x.asnumpy()
(type(a), a)

In [ ]:
nd.array(a)